name: Automatic build and release on Github with Maven
description: Build, tag, release and upload to Github using Maven
author: Lothindir
inputs:

outputs:

runs:
  using: composite
  steps:
    - name: Get Project Version from pom.xml
      uses: entimaniac/read-pom-version-action@1.0.0
      id: getVersion

    - name: Get Build Version
      uses: terradatum/semver-action@main
      id: getBuildVersion
      with:
        version: ${{ steps.getVersion.outputs.version }}
        package-manager-type: 'maven'
        bump: 'minor'
        
    - name: Build with Maven [SIM]
      run: echo "Build and release"
      shell: bash
      # uses: lothindir/github-actions-maven-release@master
      # with:
      #   ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #   git-release-bot-name: "release-bot-github "
      #   git-release-bot-email: "release.bot.github@gmail.com"
      #   release-branch-name: "main"
      #   version-minor: true
      #   skip-bot-release-check: true
      #   maven-args: "-Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
      # env:
      #   JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/

    - name: "Publish latest [SIM]"
      run: echo "Publish latest"
      shell: bash
      # uses: "marvinpinto/action-automatic-releases@latest"
      # with:
      #   repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #   automatic_release_tag: "latest"
      #   draft: true
      #   prerelease: false
      #   title: "Sprint release"
      #   files: |
      #     LICENSE
      #     target/hyde-*.jar
      #     target/hyde
      #     target/hyde.exe
      #     target/hyde-javadoc.zip

    - name: "Publish version [SIM]"
      run: echo "Publish version v${{ steps.getBuildVersion.outputs.next-version }}"
      shell: bash
      # uses: "marvinpinto/action-automatic-releases@latest"
      # with:
      #   repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #   automatic_release_tag: v${{ steps.getBuildVersion.outputs.next-version }}
      #   draft: true
      #   prerelease: false
      #   title: "Sprint release - v${{ steps.getBuildVersion.outputs.next-version }}"
      #   files: |
      #     LICENSE
      #     target/hyde-*.jar
      #     target/hyde
      #     target/hyde.exe
      #     target/hyde-javadoc.zip
