name: Main
on: [push, workflow_dispatch]
jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Local Action
        uses: ./.github/actions/automatic-release