name: Maven run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    if: "!contains(github.event.head_commit.message, '[CI SKIP]')"
    steps:
    - uses: actions/checkout@v3
=======
<<<<<<< HEAD
<<<<<<< HEAD
    if: "!contains(github.event.head_commit.message, '[CI skip]')"
    steps:
    - uses: actions/checkout@v2
=======
    if: "!contains(github.event.head_commit.message, '[CI SKIP]')"
    steps:
    - uses: actions/checkout@v3
>>>>>>> upstream/main
=======
    if: "!contains(github.event.head_commit.message, '[CI SKIP]')"
    steps:
    - uses: actions/checkout@v3
>>>>>>> upstream/main
>>>>>>> main
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn test -B
