---
name: "Create pre-release on Milestone closed"

on:
  milestone:
    types: closed

jobs:    
  pre-release:
    name: "Pre Release on Milestone"
    runs-on: "ubuntu-latest"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        uses: qcastel/github-actions-maven-release@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          #gpg-enabled: "true"
          #gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
          #gpg-key: ${{ secrets.GITHUB_GPG_KEY }}
          git-release-bot-name: "release-bot-github "
          git-release-bot-email: "release.bot.github@gmail.com"
          release-branch-name: "main"
          version-minor: true
          maven-args: "-Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
          
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
          
      - name: Get Project Version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            target/hyde-${{ steps.getVersion.outputs.version }}.jar
            target/hyde
            target/hyde.exe
