---
name: "Create pre-release on Milestone closed"

on:
  milestone:
    types: closed

jobs:    
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.31
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          version-minor: true
        env:
          JAVA_HOME: /usr/lib/jvm/java-14-openjdk/
